version: '3'
services:
  stalker:
    image: "docker-stalker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # this is only necessary on windows
      COMPOSE_CONVERT_WINDOWS_PATH: 1
    ports:
      - "8080:8080"